"""Tests for scientific structure formats: XYZ, CIF, PDB, and MATLAB MAT."""

from __future__ import annotations

from pathlib import Path

import pytest

from iterable.datatypes.cif import CIFIterable
from iterable.datatypes.pdb import PDBIterable
from iterable.datatypes.xyz import XYZIterable
from iterable.exceptions import WriteNotSupportedError

try:
    import scipy  # noqa: F401
    from scipy.io import savemat

    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False

try:
    import numpy as np

    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False

FIXTURES = Path(__file__).resolve().parent / "fixtures"


class TestXYZ:
    def test_id_and_flat(self):
        assert XYZIterable.id() == "xyz"
        assert XYZIterable.is_flatonly() is True
        assert XYZIterable.datamode == "text"

    def test_read_fixture(self):
        with XYZIterable(filename=str(FIXTURES / "2cols3rows.xyz")) as source:
            rows = list(source)
        assert len(rows) == 3
        assert rows[0] == {"element": "O", "x": 0.0, "y": 0.0, "z": 0.0}
        assert rows[1]["element"] == "H"
        assert rows[2]["element"] == "H"

    def test_read_with_extras(self, tmp_path):
        path = tmp_path / "extras.xyz"
        path.write_text("1\ncomment\nC 1.0 2.0 3.0 0.5 charge\n", encoding="utf-8")
        with XYZIterable(filename=str(path)) as source:
            rows = list(source)
        assert rows == [{"element": "C", "x": 1.0, "y": 2.0, "z": 3.0, "extra_0": 0.5, "extra_1": "charge"}]

    def test_write_round_trip(self, tmp_path):
        path = tmp_path / "out.xyz"
        records = [
            {"element": "C", "x": 1.0, "y": 2.0, "z": 3.0},
            {"element": "N", "x": 4.0, "y": 5.0, "z": 6.0},
        ]
        with XYZIterable(filename=str(path), mode="w") as dest:
            dest.write_bulk(records)
        text = path.read_text(encoding="utf-8")
        assert text.startswith("2\n")
        assert "generated by iterabledata" in text
        with XYZIterable(filename=str(path)) as source:
            assert list(source) == records


class TestCIF:
    def test_id_and_flat(self):
        assert CIFIterable.id() == "cif"
        assert CIFIterable.is_flatonly() is True

    def test_read_atom_site(self):
        with CIFIterable(filename=str(FIXTURES / "sample.cif")) as source:
            rows = list(source)
        assert len(rows) == 3
        assert rows[0]["type_symbol"] == "O"
        assert rows[0]["label_atom_id"] == "O1"
        assert rows[0]["Cartn_x"] == 0.0
        assert rows[1]["type_symbol"] == "H"

    def test_missing_atom_site_raises(self, tmp_path):
        path = tmp_path / "empty.cif"
        path.write_text("data_x\n_cell.length_a 10.0\n", encoding="utf-8")
        with pytest.raises(ValueError, match="atom_site"):
            CIFIterable(filename=str(path))

    def test_write_not_supported(self, tmp_path):
        path = tmp_path / "out.cif"
        path.write_text("data_x\n", encoding="utf-8")
        with pytest.raises(WriteNotSupportedError):
            CIFIterable(filename=str(path), mode="w")


class TestPDB:
    def test_id_and_flat(self):
        assert PDBIterable.id() == "pdb"
        assert PDBIterable.is_flatonly() is True

    def test_read_atoms(self):
        with PDBIterable(filename=str(FIXTURES / "sample.pdb")) as source:
            rows = list(source)
        assert len(rows) == 4
        assert rows[0]["record_type"] == "ATOM"
        assert rows[0]["name"] == "N"
        assert rows[0]["resName"] == "ALA"
        assert rows[0]["chainID"] == "A"
        assert rows[0]["x"] == 1.0
        assert rows[0]["element"] == "N"
        assert rows[0]["model"] == 1
        assert rows[2]["record_type"] == "HETATM"
        assert rows[3]["model"] == 2

    def test_model_filter(self):
        with PDBIterable(filename=str(FIXTURES / "sample.pdb"), options={"model": 2}) as source:
            rows = list(source)
        assert len(rows) == 1
        assert rows[0]["serial"] == 4
        assert rows[0]["model"] == 2

    def test_write_basic_atom(self, tmp_path):
        path = tmp_path / "out.pdb"
        record = {
            "record_type": "ATOM",
            "serial": 1,
            "name": "CA",
            "resName": "GLY",
            "chainID": "A",
            "resSeq": 1,
            "x": 1.5,
            "y": 2.5,
            "z": 3.5,
            "element": "C",
        }
        with PDBIterable(filename=str(path), mode="w") as dest:
            dest.write(record)
        with PDBIterable(filename=str(path)) as source:
            rows = list(source)
        assert len(rows) == 1
        assert rows[0]["name"] == "CA"
        assert rows[0]["resName"] == "GLY"
        assert rows[0]["x"] == pytest.approx(1.5)
        assert rows[0]["element"] == "C"


@pytest.mark.skipif(not (HAS_SCIPY and HAS_NUMPY), reason="scipy/numpy not available")
class TestMAT:
    def test_id_and_tables(self, tmp_path):
        from iterable.datatypes.mat import MATIterable

        path = tmp_path / "single.mat"
        savemat(str(path), {"data": np.array([[1.0, 2.0], [3.0, 4.0]])})
        assert MATIterable.id() == "mat"
        assert MATIterable.is_flatonly() is True
        assert MATIterable.has_tables() is True
        with MATIterable(filename=str(path)) as source:
            assert source.list_tables() == ["data"]
            rows = list(source)
        assert rows == [{"col0": 1.0, "col1": 2.0}, {"col0": 3.0, "col1": 4.0}]

    def test_1d_values(self, tmp_path):
        from iterable.datatypes.mat import MATIterable

        path = tmp_path / "vec.mat"
        savemat(str(path), {"vals": np.array([10.0, 20.0, 30.0])})
        with MATIterable(filename=str(path)) as source:
            assert list(source) == [{"value": 10.0}, {"value": 20.0}, {"value": 30.0}]

    def test_multi_variable_requires_selection(self, tmp_path):
        from iterable.datatypes.mat import MATIterable

        path = tmp_path / "multi.mat"
        savemat(str(path), {"a": np.array([1.0]), "b": np.array([2.0])})
        with pytest.raises(ValueError, match="table=|variable="):
            MATIterable(filename=str(path))
        with MATIterable(filename=str(path), options={"variable": "b"}) as source:
            assert list(source) == [{"value": 2.0}]
            assert "a" in source.list_tables()
            assert "b" in source.list_tables()

    def test_write_not_supported(self, tmp_path):
        from iterable.datatypes.mat import MATIterable

        path = tmp_path / "w.mat"
        savemat(str(path), {"a": np.array([1.0])})
        with pytest.raises(WriteNotSupportedError):
            MATIterable(filename=str(path), mode="w")

    def test_missing_scipy_message(self, monkeypatch):
        import iterable.datatypes.mat as mat_mod

        monkeypatch.setattr(mat_mod, "HAS_SCIPY", False)
        with pytest.raises(ImportError, match=r"iterabledata\[mat\]"):
            mat_mod.MATIterable(filename="unused.mat")
